# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWTwC-LkivmvcHmPLgWSCejRzHB47IL0
"""

#THIS IS ALL ABOUT DATAFRAMES

#PANDA SERIES
# a series is a 1d array which hold any data type. The axis labels are collectively called the index

import numpy as np
import pandas as pd

labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([15,16,17])
dic = {1:10,2:20,3:30}

pd.Series(my_list) #here indexes are called as labels

pd.Series(my_list,index=labels) # here we have put labels as indexes which we have created

pd.Series(arr) #we cant send 2d array in it as series is 1d itself

pd.Series(dic)

#DATA FRAME
# combination of multiple series is known as data frame

#Creation of data frame
data = {
    'Name':['John', 'Anna', 'Peter' ,'Linda'],
    'Location':['New York', 'Paris', 'Berlin', 'London'],
    'Age':[24,13,53,33],
    'Salary': [65000,70000,62000,85000]
}

df=pd.DataFrame(data)
df

data_list = [
    ['John', 'New York', 24, 65000],
    ['Anna', 'Paris', 13, 70000],
    ['Peter', 'Berlin', 53, 62000],
    ['Linda', 'London', 33, 85000]
]

columns = ['Name', 'Location', 'Age', 'Salary']

df2 = pd.DataFrame(data_list, columns=columns)

df2

#selection and indexing of columns
df2['Name']

df2[['Age','Name']]

#Creation of new col
df2['Designation']=['doctor','eng','eng','eng']
df2

#remove a col
df2.drop('Age',axis=1)

#very imp note axis=1 is used for cols and axis=0 is used for rows
df2

#To actually delete col and row from table we use "inplace=True"
df2.drop('Designation', axis=1 , inplace=True)
df2

#now droping the rows
df2.drop(0,axis=0)

#Selection of rows
df2.loc[0]

df2.loc[[0,1]]

df2.iloc[0]

#Selecting subsets of rows and col
df2.loc[[0,1]][["Location","Salary"]]

df2.loc[[2,3]][["Name","Age"]]

#Conditional Selection
df2[df2["Age"]>30]

df2[(df2['Age']>30) & (df2['Location']=='Berlin')]

#HANDLING MISSING DATA

data = {
    'A' : [1,2,np.nan,4,5],
    'B' : [1,2,3,4,5],
    'C' : [1,2,3,np.nan,np.nan],
    'D' : [1,np.nan,np.nan,np.nan,5]
} #np.na are null values
df3=pd.DataFrame(data)
df3

#Finding Missing Data
df3.isna()

df3.isna().sum()#it counted how many null values are in columns

df3.isna().any() #means each col has null values

#Removing NUll Values or Missing Data
#it works on row basis
df3.dropna() # all the values in row are droped where they have null values except
#the second row

df3.dropna(thresh=3) #thresh is like a limit means
#remove rows except which has 3 non null values

#Filling The Missing Data

#filling null values with 0
df3.fillna(0)

#filling missing data with different values in each col
values={'A':0,'B':100,'C':200,'D':300}
df3.fillna(value=values)

#filling values with mean
df3.fillna(df3.mean())

