# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9N1AkqDt-zlnCgaBkd6USrvCFrLflSn
"""

#PANDAS

#MERGING, JOINING AND CONCATINATION

import numpy as np
import pandas as pd

employees = pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['bob','jake','lisa','sue','peter'],
    'department':['accounting','engineering','engineering','hr','IT']})

#Data frame 2: Salary Information
salaries=pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[70000,80000,60000,90000,100000],
    'bonus':[5000,10000,7000,8000,12000]})

employees

salaries

pd.merge(employees,salaries,how='inner',on='employee_id')#how ="inner" means will merge common parts from both the tables

# how="outer" means will merge on the basis of column or employee id
pd.merge(employees,salaries,how='outer',on='employee_id')

pd.merge(employees,salaries,how='left',on='employee_id')#merging based on emp id

pd.merge(employees,salaries,how='right',on='employee_id')#merging based on salaries

#CONCATINATION OF 2 DATAFRAMES
df1=pd.DataFrame({
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3'],
    'C':['C0','C1','C2','C3']
})

df2=pd.DataFrame({
    'A':['A4','A5','A6','A7'],
    'B':['B4','B5','B6','B7'],
    'C':['C4','C5','C6','C7']
})

df1

df2

pd.concat([df1,df2]) #based on cols

pd.concat([df1,df2],axis=1)#based on rows

# JOINING DATAFRAMES
df1=pd.DataFrame({
    'name':['bob','jake','lisa','sue'],
    'index':[1,2,3,4]
})

df2=pd.DataFrame({
    'score':[70,80,60,90],
    'index':[2,3,4,5]
})

df1

df2

df1.join(df2,how='outer',lsuffix='_left',rsuffix='_right')

#GROUP BY AGGREGATION

data = {
    'Category':['A','A','B','B','A','B', 'A' , 'B'],
    'Stores':['Store1','Store2','Store1','Store2','Store1','Store2','Store1', 'Store2'],
    'Sales':[100,150,200,250,300,350,120,180],
    'Quantity':[5,10,15,20,25,30,35,36],
    'Date':pd.date_range('2023-01-01',periods=8)

}
df=pd.DataFrame(data)

df

#group by category and calculate the sum of sales
cat=df.groupby('Category')['Sales']
for i,v in cat:
    print(i)
    print(v)

df.groupby('Category')['Sales'].sum()

#group by stores and calculate the sum of sales
df.groupby('Stores')['Sales'].sum()
#there ara two types of data qualitative and qunatitaive(numbers)
#we usally do group by categorical data (qualitative data)

#group by multiple columns
#group by category and store
df.groupby(['Category','Stores'])['Sales'].sum()

# AGGREGATION -> it means when u are finding result by combining  multiple things
# Basic Agg fn are mean, mode , median ,Standard deviation ,etc

df['Sales'].mean()

df['Sales'].median()

df['Sales'].mode()

df['Sales'].min()

#we have a "".agg()" fn where we can find multiple things at same time
df['Sales'].agg(['mean','median','min','max'])

# PIVOT TABLES

data = {
    'Date':pd.date_range('2023-01-01',periods=20),
    'Product':['A','B','C','D']*5,
    'Regions':['North','South','East','West','North','South','East','West','North','South','East','West',
               'North','South','East','West','North','South','East','West'],
    'Sales':np.random.randint(100,1000,20),
    'Units':np.random.randint(10,100,20),
    'Rep':['John','Marry','Bob','Alice','John','Marry','Bob','Alice','John','Marry',
           'Bob','Alice','John','Marry','Bob','Alice','John','Marry','Bob','Alice'],
}

df=pd.DataFrame(data)
df['Month']=df['Date'].dt.month_name()
df['Quarter']='Q'+df['Date'].dt.quarter.astype(str)

df

pd.pivot_table(df,index='Regions',values='Sales',columns="Product",aggfunc='median')

#pivot tables are used to create heat maps
pd.pivot_table(df,index='Regions',values=['Sales','Units'],columns="Product",aggfunc='median')
# note when u are using agg fn values should be numeric

# CROSS TABS ->same as pivot table but a baisc diff is there
# we use here counting functions instead of aggregation fn
pd.crosstab(df['Regions'],df['Product'])

# OPERATIONS

# DATA FRAME BASIC OPERATIONS
df=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})
df

df.shape

df.columns

df.info()

df.describe()

df['A']+10

# DATAFRAME APPLYING FUNCTIONS

def sqr(x):
  return x*2

df['D']=df['B'].apply(sqr)
df

df['D']=df['B'].apply(lambda x : x**2)

df

