# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NfTHbesxbqEesXdOT-0WigzUSXAXQNJ
"""

#Array Operations

import numpy as np

#Arithmatic operations

a1 = np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

a1+a2 #to perform opeartions array size must be same

a2-a1

a1*a2

a1/a2

a1//a2

a1**a2

#BroadCasting

import numpy as np
l = [10,20,30,40]
arr=np.array(l)

arr+10 #this is the concept of broadcasting wwhen u want to add to all the elemnts

#Deep and Shallow Copy

a = np.arange(1,21)
 a

slice = a[:5]
slice=slice*10

slice

a

b=a.copy()

b[0]=99

b

a

#Matrix Operations

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

a*b

a@b #real matrix multiplication

np.dot(a,b)

a.T # mtaarix transpose

a

#Advanced Array Manipulation

#Stacking Array

a =np.array([1,2,3,4])
b= np.array([5,6,7,8])

np.vstack((a,b))

np.hstack((a,b))

np.column_stack((a,b))

#Splitting Array

c=np.arange(16).reshape(4,4)
c

np.hsplit(c,2)

a=np.vsplit(c,4)

for i in a:
  print(i)

#NUMPY EXERCISES

#valid SUDOKU

import numpy as np

s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

#suduko is valid when its sum comes 45 for each row and col
#and also valid when its 3*3 matrix sum also should comes as 45

b=np.sum(s,axis=1)#rows axis is 1 for sum
b

b==45

#another way for rows using loop
for i in b:
  if i !=45:
    print("not valid sudoku")
else:
  print("valid Sudoku")

#now for doing cloumns
c=np.sum(s,axis=0)#columns axis =1 for sum
c

c==45

#another way for rows using loop
for i in c:
  if i !=45:
    print("not valid sudoku")
else:
  print("valid Sudoku")

#now checking suduko for 3*3 matrix
for i in range(0,9,3):
  for j in range(0,9,3):
    n=s[i:i+3,j:j+3]
    print(n.sum())

#Some General Questions of NUMPY ARRAY

# columns[AGE,MATH MARKS,SCIENCE MARKS]
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,78],
    [20,90,85]
    ])

np.mean(data[:,0]) # avg of age

data[:,1] #extracting maths marks of all studnets

np.max(data[:,2]) #getting highest science marks

# get details of student who scored more than 90 in maths
data[data[:,1] > 90]

#increase  maths marks of all students by 5
data[:,1] + 5

#find how many students are yonger than 19
len(data[data[:,0] < 19])

#calculate the avg marks of each subject(col-wise mean)
np.mean(data[:,1:3],axis=0)

#get data of students who scored at least 80 in both subjects
data[(data[:,1]>=80) & (data[:,2]>=80)]

#replace all science marks < 75 with 0
data[:,2][data[:,2] < 75]=0

data

