# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ohd-LcWRtsoeG_Ub8R2ZY41i61yGnUQ
"""

import numpy as np

#Numpy Indexing And slicing Of Vectors

arr=np.arange(11,21)
print(arr)

arr[6]

#slicing is like removing a portion or dealing with subarray

arr[1:5]

#Numpy Indexing And Slicing Of Matrix

arr=np.arange(1,31)
print(arr)

arr=arr.reshape(6,5)
print(arr)

arr[0]

arr[1][0]

arr[1]

arr[0:2,1:4]

arr[3:6,3:5]

#Boolean Indexing

arr = np.arange(10,20)

print(arr)

bool_index=arr%2==0

bool_index

arr= arr[bool_index]

arr # false values are reomved only true values are left



