# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_g3ddf3T2lAn-A3L3AXTsq-Pv8ixuWy8
"""

import numpy as np

#Basic Array Creation

arr=np.array([1,2,3,4])
print(arr)

a =[1,2,3,4,"hello"]
print(a)

l=[[1,2,3,],[2,5,6]]
np.array(l)

#Array Generation Function

np.arange(1,11,2)

arr=np.zeros((3,3))

arr

#random generation function

np.random.randint(10,20,10)

np.random.rand(10)

np.random.randn(10)

#Array attributes

arr=np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(arr)

arr.shape

arr.size

arr.dtype

#Array Methods

arr

arr.min()

arr.max()

arr.sum()

np.sum(arr,axis=0)#col wise sum

np.sum(arr,axis=1)# row wise sum

arr.mean()

arr.std()

arr.argmax()

arr.argmin()

#Reshaping and Resizing

arr=np.arange(1,31)
print(arr)

arr=arr.reshape(6,5)

arr

