# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NfTHbesxbqEesXdOT-0WigzUSXAXQNJ
"""

#Array Operations

import numpy as np

#Arithmatic operations

a1 = np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

a1+a2 #to perform opeartions array size must be same

a2-a1

a1*a2

a1/a2

a1//a2

a1**a2

#BroadCasting

import numpy as np
l = [10,20,30,40]
arr=np.array(l)

arr+10 #this is the concept of broadcasting wwhen u want to add to all the elemnts

#Deep and Shallow Copy

a = np.arange(1,21)
 a

slice = a[:5]
slice=slice*10

slice

a

b=a.copy()

b[0]=99

b

a

#Matrix Operations

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

a*b

a@b #real matrix multiplication

np.dot(a,b)

a.T # mtaarix transpose

a

#Advanced Array Manipulation

#Stacking Array

a =np.array([1,2,3,4])
b= np.array([5,6,7,8])

np.vstack((a,b))

np.hstack((a,b))

np.column_stack((a,b))

#Splitting Array

c=np.arange(16).reshape(4,4)
c

np.hsplit(c,2)

a=np.vsplit(c,4)

for i in a:
  print(i)

